.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH runner-clean 1  "runner 0.12.0" "Runner Manual"
.SH NAME
runner\-clean \- Remove caches and build artifacts
.SH SYNOPSIS
\fBrunner\-clean\fR [\fB\-y\fR|\fB\-\-yes\fR] [\fB\-\-include\-framework\fR] [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Remove caches and build artifacts
.SH OPTIONS
.TP
\fB\-y\fR, \fB\-\-yes\fR
Skip confirmation prompt
.TP
\fB\-\-include\-framework\fR
Include framework\-specific Node build dirs like `.next`
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.SH AUTHORS
Kaj Kowalski
