.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH runner-completions 1  "runner 0.12.0" "Runner Manual"
.SH NAME
runner\-completions \- Generate shell completions
.SH SYNOPSIS
\fBrunner\-completions\fR [\fB\-o\fR|\fB\-\-output\fR] [\fB\-h\fR|\fB\-\-help\fR] [\fISHELL\fR] 
.SH DESCRIPTION
Generate shell completions
.SH OPTIONS
.TP
\fB\-o\fR, \fB\-\-output\fR \fI<PATH>\fR
Write the completion script to <PATH> instead of stdout. Any existing file is overwritten
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
[\fISHELL\fR]
Target shell — bare name (`zsh`) or full path (`/usr/bin/zsh`). Defaults to `$SHELL`
.SH AUTHORS
Kaj Kowalski
