#:tombi toml-version = "v1.0.0"

[workspace]
resolver        = "3"
members         = ["crates/*"]
default-members = ["crates/cli"]

[workspace.package]
version      = "0.26.2"
edition      = "2024"
rust-version = "1.95"
repository   = "https://github.com/kjanat/runner"
license      = "MIT"

[workspace.dependencies]
# Workspace internal
runner-run-core      = { path = "crates/core", version = "0.26.2" }
runner-run-providers = { path = "crates/providers", version = "0.26.2" }
runner-run-schemes   = { path = "crates/schemes", version = "0.26.2" }

# Own
actions-rs       = "0.1"
json-schema-sort = { version = "0.1", default-features = false }

# 3rd party
anyhow        = "1"
bitflags      = "2"
clap          = "4"
clap_complete = "4"
clap_mangen   = "0.3"
colored       = "3"
glob          = "0.3"
json5         = "1"
lsp-server    = "0.10"
lsp-types     = "0.97"
schemars      = "1.2"
semver        = "1"
serde         = { version = "1", features = ["derive"] }
serde_json    = "1"
shlex         = "2"
tempfile      = "3"
terminal_size = "0.4"
toml          = { version = "1.1", default-features = false }
toml_parser   = { version = "1.1", default-features = false }
unicode-width = "0.2"
yaml-rust2    = "0.13"

[workspace.lints.clippy]
all         = { level = "deny", priority = -1 }
cargo       = { level = "deny", priority = -1 }
complexity  = { level = "deny", priority = -1 }
correctness = { level = "deny", priority = -1 }
nursery     = { level = "warn", priority = -1 }
pedantic    = { level = "warn", priority = -1 }
perf        = { level = "warn", priority = -1 }
style       = { level = "warn", priority = -1 }
suspicious  = { level = "warn", priority = -1 }

# individual
multiple_crate_versions = "allow"
redundant_pub_crate     = "allow"

[workspace.lints.rust]
elided_lifetimes_in_paths = "warn"
missing_docs              = "warn"
trivial_numeric_casts     = "warn"
unnameable_types          = "warn"
unreachable_pub           = "warn"
unsafe_code               = "deny"
unused_import_braces      = "warn"
unused_lifetimes          = "warn"
unused_qualifications     = "warn"

[workspace.lints.rustdoc]
bare_urls                    = "deny"
broken_intra_doc_links       = "deny"
invalid_codeblock_attributes = "deny"
invalid_html_tags            = "deny"
invalid_rust_codeblocks      = "deny"
private_intra_doc_links      = "deny"
redundant_explicit_links     = "warn"
unescaped_backticks          = "warn"

[profile.release]
strip = true
lto   = true
