#!/usr/bin/env bun
// Build-time site data generator.
//
// Reads the workspace-root Cargo.toml and emits a typed
// `src/lib/content/generated.ts`. This replaces the old `build.ts`
// `{{var}}` string templating with a single typed source that fails
// the build loudly if the manifest is missing or malformed — a stale
// or empty version can never ship.
//
// Only the handful of scalar `[package]` fields the site needs are
// parsed, so no TOML dependency is required. Cargo's package table is
// flat quoted scalars + a quoted-string `authors` array.

import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const cargoPath = join(here, "..", "..", "Cargo.toml");
const outPath = join(here, "..", "src", "lib", "content", "generated.ts");

function fail(msg: string): never {
	console.error(`gen-site-data: ${msg}`);
	process.exit(1);
}

const raw = await Bun.file(cargoPath).text().catch(() => fail(`cannot read ${cargoPath}`));

/** Scalars/arrays from a single `[section]` table. */
function tableOf(section: string): Record<string, string | string[]> {
	const lines = raw.split("\n");
	const out: Record<string, string | string[]> = {};
	let inSection = false;
	for (const line of lines) {
		const trimmed = line.trim();
		if (trimmed.startsWith("[")) {
			inSection = trimmed === `[${section}]`;
			continue;
		}
		if (!inSection || !trimmed || trimmed.startsWith("#")) continue;
		const eq = trimmed.indexOf("=");
		if (eq === -1) continue;
		const key = trimmed.slice(0, eq).trim();
		const val = trimmed.slice(eq + 1).trim();
		if (val.startsWith("[")) {
			out[key] = [...val.matchAll(/"([^"]*)"/g)].map((m) => m[1] ?? "");
		} else {
			const m = val.match(/^"([^"]*)"/);
			if (m) out[key] = m[1] ?? "";
		}
	}
	return out;
}

const pkg = tableOf("package");
const npm = tableOf("package.metadata.npm");

function str(rec: Record<string, string | string[]>, key: string): string | undefined {
	const v = rec[key];
	return typeof v === "string" && v.length > 0 ? v : undefined;
}

const version = str(pkg, "version") ?? fail("[package].version missing");
const cratesName = str(pkg, "name") ?? fail("[package].name missing");
const npmName = str(npm, "name") ?? cratesName;
const license = str(pkg, "license") ?? "MIT";

const repoRaw = str(pkg, "repository") ?? fail("[package].repository missing");
const repo = repoRaw.replace(/\.git$/, "").replace(/\/$/, "");
const repoShort = repo.replace(/^https?:\/\/github\.com\//, "");

const authors = pkg["authors"];
const author = Array.isArray(authors) ? authors[0] ?? "" : "";
const authorMatch = author.match(/^\s*(.+?)\s*(?:<([^>]+)>)?\s*$/);
const authorName = authorMatch?.[1] || "Kaj Kowalski";
const authorEmail = authorMatch?.[2] || "info@kajkowalski.nl";

const banner = "// GENERATED by scripts/gen-site-data.ts — do not edit.\n"
	+ "// Run `bun run gen`. Source of truth: workspace-root Cargo.toml.\n";

const body = `${banner}
export const generated = {
	version: ${JSON.stringify(version)},
	cratesName: ${JSON.stringify(cratesName)},
	npmName: ${JSON.stringify(npmName)},
	license: ${JSON.stringify(license)},
	repo: ${JSON.stringify(repo)},
	repoShort: ${JSON.stringify(repoShort)},
	authorName: ${JSON.stringify(authorName)},
	authorEmail: ${JSON.stringify(authorEmail)},
} as const;
`;

await Bun.write(outPath, body);
console.log(`gen-site-data: wrote ${outPath} (v${version})`);
