// Pure, I/O-free Cargo.toml → site-data parsing. No Bun/node APIs so
// it is unit-testable under vitest. The Bun file I/O lives only in the
// gen-site-data.ts CLI wrapper.
//
// Only the scalar `[package]` fields the site needs are parsed, so no
// TOML dependency is required: Cargo's package table is flat quoted
// scalars plus a quoted-string `authors` array.

export interface GenData {
	version: string;
	cratesName: string;
	npmName: string;
	license: string;
	repo: string;
	repoShort: string;
	authorName: string;
	authorEmail: string;
}

/** Thrown when a required `[package]` field is absent — the build must
 * fail loudly rather than emit a stale/empty value. */
export class CargoParseError extends Error {}

function tableOf(
	raw: string,
	section: string,
): Record<string, string | string[]> {
	const out: Record<string, string | string[]> = {};
	let inSection = false;
	for (const line of raw.split("\n")) {
		const trimmed = line.trim();
		if (trimmed.startsWith("[")) {
			inSection = trimmed === `[${section}]`;
			continue;
		}
		if (!inSection || !trimmed || trimmed.startsWith("#")) continue;
		const eq = trimmed.indexOf("=");
		if (eq === -1) continue;
		const key = trimmed.slice(0, eq).trim();
		const val = trimmed.slice(eq + 1).trim();
		if (val.startsWith("[")) {
			out[key] = [...val.matchAll(/"([^"]*)"/g)].map((m) => m[1] ?? "");
		} else {
			const m = val.match(/^"([^"]*)"/);
			if (m) out[key] = m[1] ?? "";
		}
	}
	return out;
}

function str(
	rec: Record<string, string | string[]>,
	key: string,
): string | undefined {
	const v = rec[key];
	return typeof v === "string" && v.length > 0 ? v : undefined;
}

export function parseCargoToml(raw: string): GenData {
	const pkg = tableOf(raw, "package");
	const npm = tableOf(raw, "package.metadata.npm");

	const required = (key: string): string => {
		const v = str(pkg, key);
		if (!v) throw new CargoParseError(`[package].${key} missing or empty`);
		return v;
	};

	const version = required("version");
	const cratesName = required("name");
	const repoRaw = required("repository");

	// Trim trailing slashes first, then a `.git` suffix, so both
	// `…/repo.git/` and `…/repo/` and `…/repo.git` normalize cleanly.
	const repo = repoRaw.replace(/\/+$/, "").replace(/\.git$/, "");
	const authors = pkg["authors"];
	const author = Array.isArray(authors) ? authors[0] ?? "" : "";
	const authorMatch = author.match(/^\s*(.+?)\s*(?:<([^>]+)>)?\s*$/);

	return {
		version,
		cratesName,
		npmName: str(npm, "name") ?? cratesName,
		license: str(pkg, "license") ?? "MIT",
		repo,
		repoShort: repo.replace(/^https?:\/\/github\.com\//, ""),
		authorName: authorMatch?.[1] || "Kaj Kowalski",
		authorEmail: authorMatch?.[2] || "info@kajkowalski.nl",
	};
}

export function renderGenerated(d: GenData): string {
	const banner = "// GENERATED by scripts/gen-site-data.ts — do not edit.\n"
		+ "// Run `bun run gen`. Source of truth: workspace-root Cargo.toml.\n";
	return `${banner}
export const generated = {
	version: ${JSON.stringify(d.version)},
	cratesName: ${JSON.stringify(d.cratesName)},
	npmName: ${JSON.stringify(d.npmName)},
	license: ${JSON.stringify(d.license)},
	repo: ${JSON.stringify(d.repo)},
	repoShort: ${JSON.stringify(d.repoShort)},
	authorName: ${JSON.stringify(d.authorName)},
	authorEmail: ${JSON.stringify(d.authorEmail)},
} as const;
`;
}
