#:schema https://gist.githubusercontent.com/kjanat/1172d9d2d6dbe7c6d9983aaabef2eea5/raw/cargo-config.bundle.json

[alias]
# one-letter
i = "install --path ."
l = "cl -- -D warnings -D clippy::all"
t = "test --all-features --all-targets"

# other short
bb  = "build --bin run --bin runner"
bbr = "bb --release"
cl  = "clippy --all-targets --all-features"
rq  = "run --quiet"
rr  = "run --release"

# other
comp = "bin-runner -- completions"
lint = "l"
meta = "metadata --format-version 1"

# features
man    = "rq --features man-gen -- man"
schema = "rq --example gen-schema --features schema-gen"

# bin commands
bin-run     = "rq --bin run"
bin-runner  = "rq --bin runner"
rbin-run    = "bin-run --release"
rbin-runner = "bin-runner --release"
runner      = "bin-runner"

# [target.<triple>]
# linker = "…"              # linker to use
# runner = "…"              # wrapper to run executables
# rustflags = ["…", "…"]    # custom flags for `rustc`
# rustdocflags = ["…", "…"] # custom flags for `rustdoc`

# [target.<cfg>]
# linker = "…"            # linker to use
# runner = "…"            # wrapper to run executables
# rustflags = ["…", "…"]  # custom flags for `rustc`

# [target.<triple>.<links>] # `links` build script override
# rustc-link-lib = ["foo"]
# rustc-link-search = ["/path/to/foo"]
# rustc-flags = "-L /some/path"
# rustc-cfg = ['key="value"']
# rustc-env = {key = "value"}
# rustc-cdylib-link-arg = ["…"]
# metadata_key1 = "value"
# metadata_key2 = "value"

[term]
hyperlinks = false
