#:schema https://gist.githubusercontent.com/kjanat/1172d9d2d6dbe7c6d9983aaabef2eea5/raw/cargo-config.bundle.json

[alias]
bb          = ["build", "--bin", "run", "--bin", "runner"]
bbr         = ["bb", "--release"]
bin-run     = ["r", "--bin", "run"]
bin-runner  = ["r", "--bin", "runner"]
cl          = ["clippy", "--all-targets", "--all-features"]
i           = ["install", "--path", "."]
l           = ["cl", "--", "-D", "warnings", "-D", "clippy::all"]
meta        = ["metadata", "--format-version", "1"]
r           = "run"
rbin-run    = ["bin-run", "--release"]
rbin-runner = ["bin-runner", "--release"]
rr          = ["run", "--release"]
t           = ["test", "--all-features", "--all-targets"]

[term]
hyperlinks = false
